# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding Starter
email: chris.eueua@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey everyone This is Keon. I am a fresh-up in coding and very happy to communicate with all of you:). I hope to learn new things here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keonchen.com" # the base hostname & protocol for your site
twitter_username: keon
github_username:  ashyglim

# Build settings
markdown: kramdown
